# Get all the lost objects.
GET http://localhost:3000/objects HTTP/1.1

###
# Get an object by its ID.
GET http://localhost:3000/objects/6529fc9003d64d6b31a422e6 HTTP/1.1

###
# Create new object.
POST http://localhost:3000/objects HTTP/1.1
content-type: application/json

{
  "name": "Debug tool",
  "description": "Weird apparatus with multiple buttons.",
  "location_found": "Somewhere",
  "found_by": "6529dd2d2ec6cdf855b9d6e4",
  "date_found": "2023-03-15T14:30:00"
}

###
# Uptade object.
PUT http://localhost:3000/objects/6529fc9003d64d6b31a422e6 HTTP/1.1
content-type: application/json

{
  "description": "Another desciption here",
  "location_found": "Outside"
}

###
# Uptade object.
PUT http://localhost:3000/objects/6529fc9003d64d6b31a422e6 HTTP/1.1
content-type: application/json

{
  "retrieved_by": "6529dd2d2ec6cdf855b9d6e1",
  "date_retrieved": "2023-03-15T14:30:00"
}

###
# Delete object.
DELETE http://localhost:3000/objects/653309b2babb3b51220ed8bd HTTP/1.1
